commerce_payment.commerce_payment_gateway.plugin.coinsnap_redirect:  
  type: commerce_payment_gateway_configuration
  mapping:
    store_id:
      type: string
      label: 'Store ID'
    api_key:
      type: string
      label: 'API Key'
